name: Keycloak CI

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
  pull_request:
  schedule:
    - cron: 0 20,23,2,5 * * *
  workflow_dispatch:

env:
  DEFAULT_JDK_VERSION: 11
  DEFAULT_JDK_DIST: temurin
  SUREFIRE_RERUN_FAILING_COUNT: 2

concurrency:
  # Only cancel jobs for PR updates
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

  legacy-store-integration-tests:
    name: Legacy Store IT
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        db: [oracle] # 'mariadb' is not always shutting down, 'mssql' container not available yet
        iteration1: ['1','2','3'] # 'mariadb' is not always shutting down, 'mssql' container not available yet
        iteration2: ['1','2','3'] # 'mariadb' is not always shutting down, 'mssql' container not available yet
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - id: integration-test-setup
        name: Integration test setup
        uses: ./.github/actions/integration-test-setup

      - name: Run base tests
        run: |
          TESTS=`testsuite/integration-arquillian/tests/base/testsuites/suite.sh database`
          echo "Tests: $TESTS"
          ./mvnw test -nsu -B -Pauth-server-quarkus -Pdb-${{ matrix.db }} -Dtest=LoginTest -pl testsuite/integration-arquillian/tests/base | misc/log/trimmer.sh

      - name: Upload JVM Heapdumps
        if: always()
        uses: ./.github/actions/upload-heapdumps

      - id: upload-surefire-reports
        name: Upload Surefire reports
        uses: ./.github/actions/upload-surefire-reports
        if: always()
        with:
          api-key: ${{ secrets.FORESIGHT_API_KEY }}
          surefire-reports-path: 'testsuite/integration-arquillian/tests/base/target/surefire-reports/*.xml'